# SPDX-FileCopyrightText: 2024 Rahul Jha
# SPDX-FileCopyrightText: 2026 Johann Christensen
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
SPDX-FileCopyrightText = ["2024 Rahul Jha", "2026 Johann Christensen"]
SPDX-License-Identifier = "GPL-3.0-or-later"
path = ["static/*.png", "templates/*.svg", "uv.lock"]
